title: "Dmytro Vorobiov"
description: "Ambient Jazz Fusion"
url: "https://dvor.me"
baseurl: ""

email: "contact@dvor.me"

social:
  - name: "tiktok"
    url: "https://www.tiktok.com/@dvor5525"
  - name: "instagram"
    url: "https://www.instagram.com/__dvor/"

streaming:
  - name: "spotify"
    url: "https://open.spotify.com/artist/4EerBY9hdFw6XSfa2zH0TH"
  - name: "apple"
    url: "https://music.apple.com/artist/dmytro-vorobiov/1825502150"
  - name: "youtube"
    url: "https://music.youtube.com/channel/UC3NvddrK6kePKoHS9HtJfzQ"
  - name: "bandcamp"
    url: "https://dmytrovorobiov.bandcamp.com"

collections:
  music:
    output: true
    permalink: /music/:name/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
theme: null
